In [1]:
import pandas as pd
import numpy as np

# import plotting libraries
import matplotlib.pyplot as plt
%matplotlib inline 

import seaborn as sns
sns.set(style="white", color_codes=True)
sns.set(font_scale=1.5)

In [2]:
from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import  MultinomialNB

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
!pip install wordcloud

In [6]:
from wordcloud import WordCloud, STOPWORDS 

In [9]:
pd.set_option('max_colwidth', 400)

In [10]:
sms = pd.read_csv(r'D:\MYLEARN\DATASETS\sms.tsv', header=None, sep='\t',names=['label', 'message'])

In [11]:
sms.sample(10)

label  \
1218   ham   
1918   ham   
2698   ham   
3782   ham   
252    ham   
745    ham   
2653   ham   
22     ham   
380    ham   
4738   ham   

                                                                                                                                                                                                     message  
1218                                                                                                                                  Damn, can you make it tonight or do you want to just wait til tomorrow  
1918                                                                                                                                         We not leaving yet. Ok lor then we go elsewhere n eat. U thk...  
2698                                                                                                                                         Can you use foreign stamps for whatever you send them off for?   
3782  Dear friends, sorry for the late information. Today is the birthday of our loving Ar.Praveesh. for more details log on to face book and see. Its his number + &lt;#&gt; . Dont miss a delicious treat.  
252                      Wen ur lovable bcums angry wid u, dnt take it seriously.. Coz being angry is d most childish n true way of showing deep affection, care n luv!.. kettoda manda... Have nice day da.  
745                                                                                                                                                          Men like shorter ladies. Gaze up into his eyes.  
2653                                                                                                                                                                           No need for the drug anymore.  
22                                                                                                                                                      So ü pay first lar... Then when is da stock comin...  
380                                                          I taught that Ranjith sir called me. So only i sms like that. Becaus hes verifying about project. Prabu told today so only pa dont mistake me..  
4738                         Nt only for driving even for many reasons she is called BBD..thts it chikku, then hw abt dvg cold..heard tht vinobanagar violence hw is the condition..and hw ru ? Any problem?

In [12]:
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

to see if there is class imbalance

In [13]:
# convert label to a numerical variable
sms['label_num'] = sms.label.map({'ham': 0, 'spam': 1})

In [14]:
sms.head(10)

label  \
0   ham   
1   ham   
2  spam   
3   ham   
4   ham   
5  spam   
6   ham   
7   ham   
8  spam   
9  spam   

                                                                                                                                                            message  \
0                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...   
1                                                                                                                                     Ok lar... Joking wif u oni...   
2       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's   
3                                                                                                                 U dun say so early hor... U c already then say...   
4                                                                                                     Nah I don't think he goes to usf, he lives around here though   
5               FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv   
6                                                                                     Even my brother is not like to speak with me. They treat me like aids patent.   
7  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune   
8     WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.   
9        Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030   

   label_num  
0          0  
1          0  
2          1  
3          0  
4          0  
5          1  
6          0  
7          0  
8          1  
9          1

In [15]:
X = sms.message
y = sms.label_num

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
# split X and y into training ans testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1) 

In [18]:
X_train.shape, X_test.shape

((4179,), (1393,))

In [19]:
vect = CountVectorizer()

In [21]:
vect.fit(X_train, y_train)

CountVectorizer()

In [22]:
X_train_dtm = vect.transform(X_train)

In [23]:
X_train_dtm.shape

(4179, 7456)

In [24]:
np.set_printoptions(linewidth=140, edgeitems=12)

In [25]:
X_train_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0,

In [50]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_dtm, y_train)

KNeighborsClassifier(n_neighbors=3)

In [51]:
X_test_dtm = vect.transform(X_test)   

y_pred     = knn.predict(X_test_dtm)

In [52]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [53]:
accuracy_score(y_test, y_pred)

0.927494615936827

In [54]:
confusion_matrix(y_test, y_pred)

array([[1208,    0],
       [ 101,   84]], dtype=int64)

In [55]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96      1208
           1       1.00      0.45      0.62       185

    accuracy                           0.93      1393
   macro avg       0.96      0.73      0.79      1393
weighted avg       0.93      0.93      0.92      1393



#### Try logistic regression

In [31]:
model = LogisticRegression()

model.fit(X_train_dtm, y_train)

LogisticRegression()

In [32]:
X_test_dtm = vect.transform(X_test)

In [33]:
y_pred = model.predict(X_test_dtm)

In [34]:
accuracy_score(y_test, y_pred)

0.9877961234745154

In [36]:
confusion_matrix(y_test, y_pred)

array([[1207,    1],
       [  16,  169]], dtype=int64)

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.99      0.91      0.95       185

    accuracy                           0.99      1393
   macro avg       0.99      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



#### try naive bayes algo

In [56]:
from sklearn.naive_bayes import MultinomialNB

In [57]:
nb = MultinomialNB()

In [58]:
nb.fit(X_train_dtm, y_train)

MultinomialNB()

In [59]:
np.set_printoptions(edgeitems=10)

In [60]:
X_train_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 

In [61]:
X_train_dtm.shape

(4179, 7456)

In [62]:
y_pred_class = nb.predict(X_test_dtm)

accuracy_score(y_test, y_pred_class)


0.9885139985642498

In [63]:
confusion_matrix(y_test, y_pred_class)

array([[1203,    5],
       [  11,  174]], dtype=int64)

In [45]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 140)  # or 199

In [49]:
sms.sample(20)

label                                                                                                                                      message  label_num
1677   ham                                                                                           Yeah, that's fine! It's £6 to get in, is that ok?           0
2153   ham                                                                Hi kindly give us back our documents which we submitted for loan from STAPATI          0
2941  spam                                                                                             You have 1 new message. Please call 08712400200.          1
290    ham  Dear,shall mail tonite.busy in the street,shall update you tonite.things are looking ok.varunnathu edukkukayee raksha ollu.but a good on...          0
2934   ham  Yo do you know anyone  &lt;#&gt;  or otherwise able to buy liquor? Our guy flaked and right now if we don't get a hold of somebody its j...          0
5472   ham                                                              Well obviously not because all the people in my cool college life went home ;_;          0
1680   ham                   Today is "song dedicated day.." Which song will u dedicate for me? Send this to all ur valuable frnds but first rply me...          0
3257   ham                       Who were those people ? Were you in a tour ? I thought you were doing that sofa thing you sent me ? Your curious sugar          0
2963   ham                                                                                                     NONE!NOWHERE IKNO DOESDISCOUNT!SHITINNIT          0
4478   ham                                                                                            Oh :-)only 4 outside players allowed to play know          0
1542   ham  Do u konw waht is rael FRIENDSHIP Im gving yuo an exmpel: Jsut ese tihs msg.. Evrey splleing of tihs msg is wrnog.. Bt sitll yuo can rae...          0
5281   ham                                                                                                       And how you will do that, princess? :)          0
4718   ham                                                                K will do, addie &amp; I are doing some art so I'll be here when you get home          0
2278   ham      Hello! How r u? Im bored. Inever thought id get bored with the tv but I am. Tell me something exciting has happened there? Anything! =/          0
2039   ham                                                                                                  Hey are we going for the lo lesson or gym?           0
3913  spam                                                       You have an important customer service announcement. Call FREEPHONE 0800 542 0825 now!          1
1760   ham                                  Do u ever get a song stuck in your head for no reason and it won't go away til u listen to it like 5 times?          0
2629   ham                                                                            Haha... They cant what... At the most tmr forfeit... haha so how?          0
2755   ham                                                                        Ok Chinese food on its way. When I get fat you're paying for my lipo.          0
1758   ham                                                                                                          Miss ya, need ya, want ya, love ya.          0

In [46]:
# vectorizer tuning
import nltk
from nltk.corpus import stopwords
from string import punctuation

# Stemmer
from nltk.stem import PorterStemmer
porter = PorterStemmer()

# lemmatizing
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()

In [47]:
# Stopwords from stopwords-json
# https://raw.githubusercontent.com/6/stopwords-json/master/dist/en.json

stopwords_json = {"en":["a","a's","able","about","above","according","accordingly","across","actually","after","afterwards","again","against","ain't","all","allow","allows","almost","alone","along","already","also","although","always","am","among","amongst","an","and","another","any","anybody","anyhow","anyone","anything","anyway","anyways","anywhere","apart","appear","appreciate","appropriate","are","aren't","around","as","aside","ask","asking","associated","at","available","away","awfully","b","be","became","because","become","becomes","becoming","been","before","beforehand","behind","being","believe","below","beside","besides","best","better","between","beyond","both","brief","but","by","c","c'mon","c's","came","can","can't","cannot","cant","cause","causes","certain","certainly","changes","clearly","co","com","come","comes","concerning","consequently","consider","considering","contain","containing","contains","corresponding","could","couldn't","course","currently","d","definitely","described","despite","did","didn't","different","do","does","doesn't","doing","don't","done","down","downwards","during","e","each","edu","eg","eight","either","else","elsewhere","enough","entirely","especially","et","etc","even","ever","every","everybody","everyone","everything","everywhere","ex","exactly","example","except","f","far","few","fifth","first","five","followed","following","follows","for","former","formerly","forth","four","from","further","furthermore","g","get","gets","getting","given","gives","go","goes","going","gone","got","gotten","greetings","h","had","hadn't","happens","hardly","has","hasn't","have","haven't","having","he","he's","hello","help","hence","her","here","here's","hereafter","hereby","herein","hereupon","hers","herself","hi","him","himself","his","hither","hopefully","how","howbeit","however","i","i'd","i'll","i'm","i've","ie","if","ignored","immediate","in","inasmuch","inc","indeed","indicate","indicated","indicates","inner","insofar","instead","into","inward","is","isn't","it","it'd","it'll","it's","its","itself","j","just","k","keep","keeps","kept","know","known","knows","l","last","lately","later","latter","latterly","least","less","lest","let","let's","like","liked","likely","little","look","looking","looks","ltd","m","mainly","many","may","maybe","me","mean","meanwhile","merely","might","more","moreover","most","mostly","much","must","my","myself","n","name","namely","nd","near","nearly","necessary","need","needs","neither","never","nevertheless","new","next","nine","no","nobody","non","none","noone","nor","normally","not","nothing","novel","now","nowhere","o","obviously","of","off","often","oh","ok","okay","old","on","once","one","ones","only","onto","or","other","others","otherwise","ought","our","ours","ourselves","out","outside","over","overall","own","p","particular","particularly","per","perhaps","placed","please","plus","possible","presumably","probably","provides","q","que","quite","qv","r","rather","rd","re","really","reasonably","regarding","regardless","regards","relatively","respectively","right","s","said","same","saw","say","saying","says","second","secondly","see","seeing","seem","seemed","seeming","seems","seen","self","selves","sensible","sent","serious","seriously","seven","several","shall","she","should","shouldn't","since","six","so","some","somebody","somehow","someone","something","sometime","sometimes","somewhat","somewhere","soon","sorry","specified","specify","specifying","still","sub","such","sup","sure","t","t's","take","taken","tell","tends","th","than","thank","thanks","thanx","that","that's","thats","the","their","theirs","them","themselves","then","thence","there","there's","thereafter","thereby","therefore","therein","theres","thereupon","these","they","they'd","they'll","they're","they've","think","third","this","thorough","thoroughly","those","though","three","through","throughout","thru","thus","to","together","too","took","toward","towards","tried","tries","truly","try","trying","twice","two","u","un","under","unfortunately","unless","unlikely","until","unto","up","upon","us","use","used","useful","uses","using","usually","uucp","v","value","various","very","via","viz","vs","w","want","wants","was","wasn't","way","we","we'd","we'll","we're","we've","welcome","well","went","were","weren't","what","what's","whatever","when","whence","whenever","where","where's","whereafter","whereas","whereby","wherein","whereupon","wherever","whether","which","while","whither","who","who's","whoever","whole","whom","whose","why","will","willing","wish","with","within","without","won't","wonder","would","wouldn't","x","y","yes","yet","you","you'd","you'll","you're","you've","your","yours","yourself","yourselves","z","zero"]}

In [48]:
stopwords_json_en = set(stopwords_json['en'])
stopwords_nltk_en = set(stopwords.words('english'))
stopwords_punct   = set(punctuation)

In [49]:
# Combine the stopwords. Its a lot longer so I'm not printing it out...
stoplist_combined = set.union(stopwords_json_en, stopwords_nltk_en, stopwords_punct)

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [58]:
vect = TfidfVectorizer(stop_words=stoplist_combined, 
                       token_pattern='(?u)\\b[a-zA-Z]{3,}\\b')

In [59]:
vect

TfidfVectorizer(stop_words={'!', '"', '#', '$', '%', '&', "'", '(', ')', '*',
                            '+', ',', '-', '.', '/', ':', ';', '<', '=', '>',
                            '?', '@', '[', '\\', ']', '^', '_', '`', 'a', "a's", ...},
                token_pattern='(?u)\\b[a-zA-Z]{3,}\\b')

In [60]:
vect.fit(X_train)                     # create the fitted vocabulary
X_train_dtm = vect.transform(X_train) # create the document-term matrix

D:\ANACONDA1\lib\site-packages\sklearn\feature_extraction\text.py:383: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['mon'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '


In [61]:
# Number of rows = number of training samples,
# number of columns = features
X_train_dtm.shape

(4179, 5943)

In [62]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x5943 sparse matrix of type '<class 'numpy.float64'>'
	with 7238 stored elements in Compressed Sparse Row format>

In [63]:

nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

y_pred_class = nb.predict(X_test_dtm)
accuracy_score(y_test, y_pred_class)

0.9691313711414213